### ISSUE TITLE
Add description of heparin level calculation to README.md

### ISSUE THREAD

**Issue by kubantjan** [mild-blue/breviary-backend#2]
similarily like is done in #1 for insuline

**Comment by kubantjan** [comment]
@tomaskourim  tohle mam pocit, ze jsi nekdy delal, ted to ale nevidim, mame to nekde sepsany?

**Comment by tomaskourim** [comment]
> 
> 
> @tomaskourim tohle mam pocit, ze jsi nekdy delal, ted to ale nevidim, mame to nekde sepsany?

Je to popsane v docstringu u jednotlivych funkci. Asi by ale stalo za to dat to na nejake centralni misto. A mozna by to mohla zkusit @carishkaa v ramci seznamovani se s aplikaci, ne?
