### ISSUE TITLE
Add option to manualy update heparin dosage

### ISSUE THREAD

**Issue by tomaskourim** [mild-blue/breviary-backend#42]
Pridat moznost pro uzivatele manualne upravit a prepsat hodnoty, ktere aplikace doporuci. Chceme umet upravit bolus i kontinualni davku. A chceme si vse ukladat do databaze, tedy tu puvodne doporucovanou hodnotu i tu zmenu, kterou uzivatel provedl.

**Comment by marazt** [comment]
Tj. do tabulky `heparin_dosages` pridat dva nove sloupecky pro moznost korekce vypocitanych hodnot:

- Pridat migraci tabulky `heparin_dosages` - dva nove sloupce `corrected_dosage_continuous NUMERIC` a `corrected_dosage_bolus NUMERIC`
- Upravit entitu `HeparinDosageEntity`
- Upravit DTO `HeparinPatientDtoOut`, aby vracela tyto dve nove hodnoty a i ID daneho DB zaznamu kvuli moznosti editace
- Pridat metodu do `HeparinPatientService` pro moznost pridani korekce
- Pridat POST metodu do `HeparinRecommendationController`
- Testy na service a controller.
