### ISSUE TITLE
Heparin recommendation not working

### ISSUE THREAD

**Issue by tomaskourim** [mild-blue/breviary-backend#60]
z BE chodi NaN
![image](https://user-images.githubusercontent.com/50045455/109550285-5bafd100-7acf-11eb-88f4-ed9155744e48.png)

**Comment by carishkaa** [comment]
uz vidim v cem je problem.
pri vytvareni pacienta by se mely taky vyplnovat solutionHeparinUnits = 25 000 a solutionMilliliters = 500, ale misto toho se posilaji nuly a vsechno se pak pocita spatne. 
jsou hodnoty 25000 a 500 defaultni? muzu tam pridat nejakou podminku, ze pokud obdrzime nulu, tak tam zapiseme ty defaultni hodnoty.

**Comment by tomaskourim** [comment]
> 
> 
> uz vidim v cem je problem.
> pri vytvareni pacienta by se mely taky vyplnovat solutionHeparinUnits = 25 000 a solutionMilliliters = 500, ale misto toho se posilaji nuly a vsechno se pak pocita spatne.
> jsou hodnoty 25000 a 500 defaultni? muzu tam pridat nejakou podminku, ze pokud obdrzime nulu, tak tam zapiseme ty defaultni hodnoty.

Fajn, dobre zjisteni. 25000 a 500 jsou defaultni (pouzivane v IKEM), vyhledove urcite chceme mit moznost to upravit. Udelal bych tedy i na FE (@misslecter ) pri pridani pacienta kolonky na ty 2 veci a defaultne je vyplnil na 25 000 a 500.
